env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  semi: 'off'
  quotes: 'off'
  no-use-before-define: 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/semi': error
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: false
