root: true
extends:
  - '@floydspace/eslint-config/lib'
  - '@floydspace/eslint-config/jest'
rules:
  '@typescript-eslint/naming-convention': off
  jest/no-conditional-expect: off
overrides:
  - files:
      - 'examples/**/*.[tj]s'
    rules:
      import/no-unresolved: off
      no-promise-executor-return: off
      no-console: off
