name: pull

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 7
      - run: npm ci
      - run: npm test
      - run: npm run test:e2e
      - name: Upload e2e test artifacts
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: e2e-test-artifact
          path: |
            .test-artifacts/**/.serverless/*.json
            .test-artifacts/**/.serverless/*.zip
          retention-days: 7
      - run: npm run build --if-present
